### ISSUE TITLE
Add chart zoom lock for mobile

### ISSUE THREAD

**Issue by richardgoater** [theosanderson/covince#89]
I finally agree that the zoom on mobile is too easy to accidentally apply. Thought of a solution that the 'reset chart zoom' button could become a tri-state of enable/disable/reset chart zoom. It takes some attention away from the map button, but should be ok.

**Comment by theosanderson** [comment]
That's a really neat solution!

**Comment by richardgoater** [comment]
an alternative is sliders, I really like the slider on mobile here: https://impfdashboard.de/

**Comment by theosanderson** [comment]
I think the tooltip slider is cool. (It's a bit different from our tooltip because it doesn't block the page, so not sure how directly implementable it is)

For me the slider doesn't solve one of the issues here, which is that mobile interaction involves a lot of "click and drag actions" and it is unexpected that click and drag triggers a zoom here, even if there is another way of exploring the tooltip.
